{application,hextille,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"Module for common math operations in hexagonal grids."},
              {modules,['Elixir.Hextille.Application','Elixir.Hextille.Cube',
                        'Elixir.Hextille.HexGrid','Elixir.Hextille.Logger',
                        'Elixir.Hextille.Offset']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]},
              {mod,{'Elixir.Hextille.Application',[]}}]}.
